BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS';

    EXCEPTION
        WHEN OTHERS THEN
        IF SQLCODE = -00942 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

CREATE TABLE DEPARTMENTS (

    ID_DEPARTMENT NUMBER(8, 0) CONSTRAINT PK_DEPARTMENTS PRIMARY KEY,
    DS_NAME VARCHAR2(20 CHAR) NOT NULL
);

INSERT INTO DEPARTMENTS(
    ID_DEPARTMENT,
    DS_NAME
  )
VALUES
  (
    1,
    'Marketing Department'
  );

INSERT INTO DEPARTMENTS(
    ID_DEPARTMENT,
    DS_NAME
  )
VALUES
  (
    2,
    'Finance Department'
  );

INSERT INTO DEPARTMENTS(
    ID_DEPARTMENT,
    DS_NAME
  )
VALUES
  (
    3,
    'Sales Department'
  );


ALTER TABLE MANAGERS ADD ID_DEPARTMENT NUMBER(8);

UPDATE MANAGERS
SET ID_DEPARTMENT = 2
where ID_MANAGER = 1;

UPDATE MANAGERS
SET ID_DEPARTMENT = 3
where ID_MANAGER = 2;

UPDATE MANAGERS
SET ID_DEPARTMENT = 1
where ID_MANAGER = 3;

ALTER TABLE MANAGERS ADD CONSTRAINT FK_MANAGERS_DEPARTMENT FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENTS(ID_DEPARTMENT);
