
  CREATE TABLE "STUDY1"."USERS"
   (	"ID_USER" NUMBER,
	"DS_USER" VARCHAR2(255 BYTE),
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;